# Generated by Django 2.0.3 on 2018-03-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180315_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
