# Generated by Django 2.0.3 on 2018-03-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180315_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrating',
            old_name='bookid',
            new_name='rated_book',
        ),
    ]
