# Generated by Django 2.0.3 on 2018-03-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180316_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrating',
            old_name='rated_book',
            new_name='rtd_book',
        ),
    ]
