# Generated by Django 2.0.3 on 2018-03-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180313_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bigImage',
            field=models.ImageField(blank=True, upload_to='data'),
        ),
        migrations.AddField(
            model_name='book',
            name='smallImage',
            field=models.ImageField(blank=True, upload_to='data'),
        ),
    ]
