# Generated by Django 2.0.3 on 2018-03-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180316_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bigImage',
            field=models.ImageField(blank=True, upload_to='books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='smallImage',
            field=models.ImageField(blank=True, upload_to='books'),
        ),
    ]
