# Generated by Django 2.0.3 on 2018-03-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20180316_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='middleImage',
            field=models.ImageField(blank=True, upload_to='books'),
        ),
    ]
