# Generated by Django 2.0.3 on 2018-03-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20180317_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bigImage',
            field=models.ImageField(blank=True, upload_to='books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='middleImage',
            field=models.ImageField(blank=True, upload_to='books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='smallImage',
            field=models.ImageField(blank=True, upload_to='books'),
        ),
    ]
